FROM php:7.4

RUN apt-get update -y && apt-get install -y openssl zip unzip git

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN docker-php-ext-install pdo pdo_mysql

WORKDIR /news-feed/backend
COPY . .
RUN composer install

EXPOSE 8000
CMD php artisan serve --port=8000 --host=0.0.0.0
